# Generated by Django 5.0.4 on 2024-04-27 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='empleados',
        ),
        migrations.AddField(
            model_name='empleados',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.areas'),
        ),
    ]
