# Generated by Django 5.0.4 on 2024-04-27 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_remove_areas_empleados_empleados_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name_plural': 'áreas'},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name_plural': 'empleados'},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='empleado',
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.cargo'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='áreas'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
