# Generated by Django 5.0.4 on 2024-05-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_areas_options_alter_empleados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='areas',
            name='empleados',
            field=models.ManyToManyField(blank=True, null=True, to='empresa.empleados'),
        ),
    ]
